#!/bin/bash

touch ~/.bscripts/index.html
find -L ~/.bscripts -maxdepth 1 -type f -name "*~" -exec rm -f {} +
find -L ~/.bscripts -maxdepth 1 -type f -exec chmod 755 {} +
chmod 666 ~/.bscripts/index.html
